### ISSUE TITLE
gnuplot 5.0.6 missing or wrong libraries

### ISSUE THREAD

**Issue by nlosacco** [conda-forge/gnuplot-feedstock#6]
On my system gnuplot fails to start complaining about wrong library versions:

```
dyld: Library not loaded: @rpath/libpng16.16.dylib

  Referenced from: /anaconda/bin/gnuplot

  Reason: Incompatible library version: gnuplot requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0
Abort trap: 6
```

or missing libraries e.g. is looking for libgd.3.dyld (I cannot paste the original error message)

**Comment by croth1** [comment]
can you add the output of `conda list libpng`?

**Comment by nlosacco** [comment]
Here you go:

```
# packages in environment at /anaconda:
#
libpng                    1.6.27                        0
```

**Comment by croth1** [comment]
I just checked on my mac - the gnuplot package seems to be ok, but it's important that all dependencies are installed from the conda-forge channel and not from the defaults channel.

In one of my older environments I had a problem that conda resolved the dependencies wrongly and pulled in cairo from the defaults channel. I solved the problem by first doing `conda install cairo -c conda-forge` followed by `conda install gnuplot -c conda-forge`.

Can you check that `conda install gnuplot` does not pull in dependencies from `defaults`?

**Comment by nlosacco** [comment]
Hi Christian,

thanks for your reply.
In fact Gnuplot from conda-forge (I'm trying to install 5.2.0 at the
moment) does pull a bunch of dependencies from the default channel. I tried
to solve this by removing the default channel (OT: by the way, I cannot
find the check box next to the channel name in Anaconda Navigator, then I
had to remove the default channel and now I'm trying to figure out how to
put it back again) but there is a conflict problem with the installed
anaconda package, requiring freetype 2.5.5 2.

Best,

N


2017-09-01 17:38 GMT+02:00 Christian Roth <notifications@github.com>:

**Comment by nlosacco** [comment]
Alright, I solved by creating a new blank environment without the anaconda package and installing Gnuplot 5.2.0 from conda-forge after deleting channel defaults.
BTW, is there a reason why condo-forge Gnuplot comes without the wxt terminal?
Do previous versions have wxt?
Finally is there a workaround to install in an environment where anaconda exists?

**Comment by croth1** [comment]
Alright, I solved by creating a new blank environment without the anaconda package and installing Gnuplot 5.2.0 from conda-forge after deleting channel defaults.

> BTW, is there a reason why condo-forge Gnuplot comes without the wxt terminal?

When I started packaging gnuplot for bioconda I had no particular need for it, so I didn't spend the extra effort. Do you need it? If so, we can work on it.

> Do previous versions have wxt?

At least not the ones I packaged (>5.0 in bioconda and conda-forge)

> Finally is there a workaround to install in an environment where anaconda exists?

Depends - if the packages that depend on `freetype 2.5.5` have a pendant in conda-forge and can be updated to conda-forge's version, it should work. If not you either have to package them or ask in conda-forge/staged-recipes for help with packaging.

**Comment by croth1** [comment]
I will close this due to inactivity.
